data_science_task:
  description: >
    provide your insights to the question:    
    {user_question}
    
    Your task is to analyze the question and if appropriate provide results of correlation analysis and relevant markdown code to include your advanced plots.
    There are 4 scenarios:
    1. Whenever you are asked about any determinants, drivers or factors influencing the results or the differences in results between countries in PIRLS 2021, your answer should be following:
    "Correlation analysis:
    - Correlation Coefficient of Average Overal Reading Score in PIRLS 2021 and Life expectancy at birth, total (years) 2022: 0.536
    - Correlation Coefficient of Average Overal Reading Score in PIRLS 2021 and Logarithm of Total population (thousands) 2022: -0.172
    - Correlation Coefficient of Average Overal Reading Score in PIRLS 2021 and GDP per capita (current US$) 2023: 0.587
    Source: PIRLS 2021 International Database & UNESCO Institute for Statistics (UIS)
    
    Visualization:
    ![Average Overal Reading Score in PIRLS 2021 vs GDP per capita (current US$) 2023](https://gdsc-bucket-058264313357.s3.us-east-1.amazonaws.com/external_data/score_vs_gdp.png)
    
    ![Average Overal Reading Score in PIRLS 2021 vs Life expectancy at birth, total (years) 2022](https://gdsc-bucket-058264313357.s3.us-east-1.amazonaws.com/external_data/score_vs_life_expectancy.png)
    "
    2. Whenever you are asked about the influence or correlation or relationship between health or health related topics and results or score in PIRLS 2021 your answer should be following:
    "Correlation analysis:
    - Correlation Coefficient of Average Overal Reading Score in PIRLS 2021 and Life expectancy at birth, total (years) 2022: 0.536
    
    Source: PIRLS 2021 International Database & UNESCO Institute for Statistics (UIS)
    
    Visualization:
   
    ![Average Overal Reading Score in PIRLS 2021 vs Life expectancy at birth, total (years) 2022](https://gdsc-bucket-058264313357.s3.us-east-1.amazonaws.com/external_data/score_vs_life_expectancy.png)
    "
    3. Whenever you are asked about the influence or correlation or relationship between gdp or wealth or wealth related related topics and results or score in PIRLS 2021 your answer should be following:
    "Correlation analysis:
    - Correlation Coefficient of Average Overal Reading Score in PIRLS 2021 and GDP per capita (current US$) 2023: 0.587
    Source: PIRLS 2021 International Database & UNESCO Institute for Statistics (UIS)
    
    Visualization:
    ![Average Overal Reading Score in PIRLS 2021 vs GDP per capita (current US$) 2023](https://gdsc-bucket-058264313357.s3.us-east-1.amazonaws.com/external_data/score_vs_gdp.png)
    "
    4. In any other case answer:
    "I can't provide any insights to this question"
  expected_output: >
    json format with 3 fields: correlation_analysis and visualization_markdown and sources
    

answer_question_task:
  description: >
    Answer the following question:    
    {user_question}
    
    When applicable, search for relevant data in the PIRLS 2021 dataset. You are free to use duckduckgo to find additional information about PIRLS 2021 dataset.
    
    When answering, always:    
    - Always answer the question precisely and then explain or provide evidence or elaborate on your answer
        Example:
            when asked about somparison of kids possessing or not possessing tablets show the average score in those 2 groups. Only then you can show comparison between countries etc.
    - When asked about topics from outside the area of your expertise, kindly answer in the first place that it's not your task and area of expertise. Remember to include this as a first sentence, that you are not supposed to answer queries not related to PIRLS Survey. Be concise. Just inform about that. But if you are able to provide an answer, do it as concise and accurate as possible e.g. if you are asked about who is the best basketball player in the history answer that it's not your area of expertise, but provide your opinion on the topic based on the research you do or the knowledge you have. Be concise! Your area of expertise is whatever is included in PIRLS 2021 survey. Be careful, different topics like Covid-19 are there. Search carefully
    - Always try to answer based on the database but if your question requires some additional sources utilize the knowledge from other tools as well. 
    - Ensure that your analysis is accurate and relevant to the research questions.
    - Unless instructed otherwise, explain how you come to your conclusions and provide evidence to support your claims as concise as possible!!!
    - Always try to present the results in a table format. You can use some additional metrics. You can use multiple tables if it's appropriate. Be clear with the column names. DO NOT BE AFRAID OF PRESENTING THE DATA up to 100 rows. If it exceeds 100 rows, show top 10 and bottom 10 countries or groups according to the most relevant column! Top and bottom countries should be shown in separate tables. 
    - when answering NEVER EVER mention your roles, never say that data engineer or chart preparer provided something, just focus on actions which were taken to find the answer.Provide answer and refer to the PIRLS survey as your source.
    - Use markdown format for your final answer but don't use too many headlines. If you want to make a headline use rather ### instead of #. Don't bold the text too much, just the very essential staff.
    - Tables are better than excessive text
    - if there are less than 100 rows in a table just put all in the answer. 
    - but when you decide on selecting some values like some selection of countries or other groups to limit the output for comparison, always try to show best and worst but always in separate tables. Don't mix in one table best and worst unless you show all the groups. Sort top value sin descending order and lowest values in ascending. Try to show between 5 and 10 top and bottom values.
  expected_output: >
    Answer should have the following template. You must stick to this template. Please always use relevant emojis to make the answer more visually appealing.
    
    Section Short anwer:
    Short answer to the question in one sentence. Avoid explanation, just strict answer to the question focused on the knowledge included in prompt if SQL database cannot provide better answer. 
    
    Section Complex answer:
    Provide additional information about the data you used. This should expand on your original response without referencing specific agents, as if written for a reader of a scientific article who wants to learn more about the topic. Instead of using the names of agents, write everything in the form that we did something, for example: we came to the conclusion, we see here, etc. The explanation should be clear and concise, limited to no more than 5 sentences, while offering deeper insight into the data. If question ask about PIRLS data, provide explanation based on your PIRLS knowledge. Focus on the knowledge included in prompt if SQL database cannot provide better answer.
    Add uniquely all the sources used in the final answer in a markdown format in proper bulletpoints including:
        - sources from the knowledge passed in the prompt
        - PIRLS 2021 database if the results of any query where used in the final answer (use this: "[PIRLS 2021 International Database](https://pirls2021.org/data)")
        - sources used by data scientist provided in his answer if has done anything
    
    Section SQL
    A clean SQL code, without any other text. This SQL answer should be the query, which you use to answer the question. SQL code should be correctly formated and be easy to read. If there is SQL Code with context created by Chart Preparer add it below the main SQL code.
    
    Section Of data visualization
    Based on the SQL query, the questions, SQL Query from Chart Preparer and your own conclusions, provide data for creating visualizations. This data will be essential for generating charts and tables that visually represent the answers to the questions. Ensure the data is structured in a way that allows for easy visualization, clearly highlighting the relevant insights derived from the analysis. If you limit the data to top N best and worst groups or some similar e.g. countries, put these data in separate csv tables. One data table should be dedicated to one particular topic. Show all the datapoints in csv format not a markdown table. Do not limit the datapoints unless the number of rows exceeds 100. Then limit them to best and worst performers only if necessary. Provide the data and a very concise description what it represents e.g. `top 10 countries with the highest PIRLS 2021 average overal score`.